### ISSUE TITLE
Auth0 tokeninfo is not available for new users

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#121]
<a href="https://github.com/skinkie"><img src="https://avatars3.githubusercontent.com/u/502394?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skinkie](https://github.com/skinkie)**
_Tuesday Jul 10, 2018 at 19:46 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/102_

----

Which results in:

```
Jul 10 21:41:08.108 [qtp812824849-21] WARN  c.c.d.manager.auth.Auth0Connection:59 - Could not verify user
java.io.FileNotFoundException: https://opengeo.eu.auth0.com/tokeninfo
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[na:1.8.0_172]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_172]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[na:1.8.0_172]
        at com.conveyal.datatools.manager.auth.Auth0Connection.getUserProfile(Auth0Connection.java:101) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at com.conveyal.datatools.manager.auth.Auth0Connection.checkUser(Auth0Connection.java:55) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at com.conveyal.datatools.manager.DataManager.lambda$registerRoutes$2(DataManager.java:234) [dt-v3.1.0-139-gb572b43.jar:na]
        at spark.FilterImpl$1.handle(FilterImpl.java:62) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:125) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) ~[dt-v3.1.0-139-gb572b43.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
```

**Comment by landonreed** [comment]
<a href="https://github.com/abyrd"><img src="https://avatars0.githubusercontent.com/u/112871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abyrd](https://github.com/abyrd)**
_Wednesday Jul 11, 2018 at 15:50 GMT_

----

@skinkie when you say "new users" do you mean new users of datatools-server or new users of Auth0? I have been told this is in fact an issue with new Auth0 accounts, which work differently than our older account.

**Comment by landonreed** [comment]
<a href="https://github.com/skinkie"><img src="https://avatars3.githubusercontent.com/u/502394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skinkie](https://github.com/skinkie)**
_Wednesday Jul 11, 2018 at 17:11 GMT_

----

New users of Auth0. The tokeninfo endpoint is not available anymore.

Try to set up the system by the read the docs documentation, and notice that a lot of things just do not work.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Wednesday Jul 18, 2018 at 13:06 GMT_

----

@skinkie, did you come up with a workaround for this missing endpoint?  We would certainly like to update Data Tools to work with new Auth0 clients.

**Comment by landonreed** [comment]
<a href="https://github.com/skinkie"><img src="https://avatars3.githubusercontent.com/u/502394?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skinkie](https://github.com/skinkie)**
_Wednesday Jul 18, 2018 at 13:55 GMT_

----

No workaround available, other than disabling all the authentication.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Nov 13, 2018 at 17:57 GMT_

----

The `tokeninfo` request has been removed in favor of the correct way to verify the token and retrieving the user profile from the token provided by the requesting client.
