### ISSUE TITLE
Problem with jackson when running data-tools server

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#136]
<a href="https://github.com/ilarimikkonen"><img src="https://avatars1.githubusercontent.com/u/7221736?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ilarimikkonen](https://github.com/ilarimikkonen)**
_Friday Sep 28, 2018 at 12:29 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/117_

----

Hi,

we are evaluating this editor for our OpenARMS project. After running "mvn package", two jars are produced. If I try to run the jar (e.g. java -jar target/dt-v1.0.0.jar /path/to/env.yml /path/to/server.yml) per these instructions: https://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/
we get this error: 

/datatools-server$ java -jar target/datatools-server-3.2.0-SNAPSHOT.jar /home/ilari/GTFS/datatools-server/configurations/default/env.yml /home/ilari/GTFS/datatools-server/configurations/default/server.yml
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
ilari@scrappy:~/GTFS/datatools-server$

if I ran the other created jar, server starts.. I tried with random jackson.version but this did not help.

how to fix this so we can move on? BTW, the fix-auth0-new-tenants and related datatools-ui seems to work ok with some tweaks.

BTW2, please update that (https://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/) documentation. It seems outdated.

**Comment by landonreed** [comment]
<a href="https://github.com/ilarimikkonen"><img src="https://avatars1.githubusercontent.com/u/7221736?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ilarimikkonen](https://github.com/ilarimikkonen)**
_Sunday Sep 30, 2018 at 08:50 GMT_

----

just to note that this happens at least with "dev" and "fix-auth0-new-tenants" branches. "master" branch says: no main manifest attribute.. when trying to run

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Monday Oct 01, 2018 at 15:46 GMT_

----

The `datatools-server-3.2.0-SNAPSHOT.jar ` file is the "unshaded" jar, so it doesn't contain all of the maven dependency libraries after running `mvn package`. The `dt-$some_version.jar` should be the one that is runnable. We're looking to cut a stable release this week to conclude a large development period to refactor the storage back end for the application, so hopefully this will reduce some confusion.

The log output posted above appears to be using the wrong jar file (i.e., `datatools-server-3.2.0-SNAPSHOT.jar `).
