### ISSUE TITLE
Feeds are uploaded to locale FS but downloaded from s3 bucket ?

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#25]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zbouziane](https://github.com/zbouziane)**
_Tuesday Apr 18, 2017 at 13:03 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/8_

----

```java -jar target/dt-6a27c88-dirty.jar configurations/default/env.yml configurations/default/server.yml
14:58:30.111 [main] INFO  c.c.datatools.manager.DataManager - Loading env.yml: configurations/default/env.yml
14:58:30.115 [main] INFO  c.c.datatools.manager.DataManager - Loading server.yml: configurations/default/server.yml
14:58:30.191 [main] INFO  c.c.d.manager.persistence.DataStore - /Users/zbouziane/Data/cataloguedev/mapdb/projects
14:58:30.375 [main] INFO  c.c.datatools.manager.DataManager - Initializing gtfs-api for bucket cataloguedev/gtfs/ and cache dir /Users/zbouziane/Data/cataloguedev/gtfs
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
14:58:31.078 [main] INFO  com.conveyal.gtfs.GTFSCache - Using bucket cataloguedev for GTFS Cache
14:58:31.109 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @6536ms
14:58:31.178 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...
14:58:31.179 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4000
14:58:31.182 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
14:58:31.313 [Thread-1] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@d6e9a92{HTTP/1.1,[http/1.1]}{0.0.0.0:4000}
14:58:31.316 [Thread-1] INFO  org.eclipse.jetty.server.Server - Started @6744ms
14:58:31.388 [main] WARN  c.c.d.m.c.api.GtfsApiController - No extension provided for GTFS API
14:58:31.390 [pool-1-thread-1] INFO  c.c.d.manager.jobs.FeedUpdater - Fetching feeds...
14:58:31.390 [pool-1-thread-1] INFO  c.c.d.manager.jobs.FeedUpdater - Current eTag list {}
14:58:31.405 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
14:58:31.405 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
14:58:31.405 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
14:58:31.413 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
14:58:31.413 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
14:58:31.413 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
14:58:31.417 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
14:58:31.418 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
14:58:31.418 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
14:58:31.418 [main] INFO  c.c.datatools.manager.DataManager - Registering TransitLand Resource
14:58:31.419 [main] INFO  c.c.datatools.manager.DataManager - Registering TransitFeeds Resource
14:58:31.974 [pool-1-thread-1] INFO  c.c.d.manager.jobs.FeedUpdater - No feeds updated...
14:58:42.352 [qtp891452239-15] INFO  c.c.d.m.c.api.ProjectController - found projects: 0
/api/manager/public/region
14:58:42.439 [qtp891452239-17] INFO  c.c.d.manager.persistence.DataStore - /Users/zbouziane/Data/cataloguedev/mapdb/region
14:58:45.460 [qtp891452239-20] INFO  c.c.d.m.c.api.ProjectController - found projects: 0
14:58:51.244 [qtp891452239-18] INFO  c.c.d.m.c.api.ProjectController - found projects: 0
14:59:00.327 [qtp891452239-21] INFO  c.c.d.manager.persistence.DataStore - /Users/zbouziane/Data/cataloguedev/mapdb/feedsources
14:59:00.429 [qtp891452239-20] INFO  c.c.d.m.c.api.ProjectController - found projects: 1
developer.digitalfactory@gmail.com
setting fs project
14:59:17.457 [qtp891452239-17] INFO  c.c.d.manager.persistence.DataStore - /Users/zbouziane/Data/cataloguedev/mapdb/feedversions
14:59:17.500 [qtp891452239-17] INFO  c.c.d.manager.persistence.DataStore - /Users/zbouziane/Data/cataloguedev/mapdb/externalFeedSourceProperties
developer.digitalfactory@gmail.com
14:59:44.113 [qtp891452239-20] INFO  c.c.d.m.c.api.FeedVersionController - Saving feed from upload <FeedSource tampere (10e9ec1c-a6c7-418e-95f9-9eb4d911f167)>
14:59:44.113 [qtp891452239-20] INFO  c.c.d.manager.persistence.FeedStore - Writing file to /Users/zbouziane/Data/cataloguedev/gtfs/tampere-20170418T145943+02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.zip
14:59:44.182 [qtp891452239-20] INFO  c.c.d.manager.persistence.FeedStore - Copying version to latest <FeedSource tampere (10e9ec1c-a6c7-418e-95f9-9eb4d911f167)>
14:59:44.200 [qtp891452239-20] INFO  c.c.d.manager.models.FeedVersion - New GTFS file saved: tampere-20170418T145943+02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.zip
14:59:44.209 [qtp891452239-20] INFO  c.c.d.m.c.api.FeedVersionController - Last modified: Fri Dec 02 09:44:10 CET 2016
14:59:44.214 [qtp891452239-20] INFO  c.c.d.manager.persistence.FeedStore - Downloading feed from s3
14:59:44.366 [qtp891452239-20] ERROR c.c.d.manager.persistence.FeedStore - Error downloading from s3
com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 25A928491624EB60), S3 Extended Request ID: DM7fWaJ+9bKZcoXEBrjDDBS8nwwgxQwoCek7HdEtky+y1QQxr0VnfF/B1HnZxz48gl6fPkY1h60=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1579)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1249)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1385)
	at com.conveyal.datatools.manager.persistence.FeedStore.getFeed(FeedStore.java:159)
	at com.conveyal.datatools.manager.models.FeedVersion.getGtfsFile(FeedVersion.java:155)
	at com.conveyal.datatools.manager.models.FeedVersion.hash(FeedVersion.java:441)
	at com.conveyal.datatools.manager.controllers.api.FeedVersionController.createFeedVersion(FeedVersionController.java:134)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
14:59:44.989 [qtp891452239-20] INFO  c.c.d.e.j.ProcessGtfsSnapshotMerge - GTFS Snapshot Merge for feedVersion tampere-20170418T145943+02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.zip
14:59:44.991 [Thread-11] INFO  c.c.d.manager.jobs.ValidateFeedJob - Running ValidateFeedJob for tampere-20170418T145943+02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.zip
14:59:44.993 [Thread-11] INFO  c.c.d.manager.auth.Auth0Users - Auth0 getUsers URL=https://cataloguetest.eu.auth0.com/api/v2/users/auth0%7C57a1f0c5b8155e90194e5087
14:59:45.233 [Thread-11] INFO  com.conveyal.gtfs.GTFSCache - Attempting to download cached GTFS MapDB.
14:59:45.368 [Thread-11] WARN  com.conveyal.gtfs.GTFSCache - DB file for key gtfs/tampere-20170418T145943-02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167 does not exist on S3.
14:59:45.368 [Thread-11] INFO  com.conveyal.gtfs.GTFSCache - Loading feed from local cache directory...
14:59:45.368 [Thread-11] INFO  com.conveyal.gtfs.GTFSCache - Feed not found locally, downloading from S3.
14:59:45.399 [Thread-11] ERROR com.conveyal.gtfs.GTFSCache - Could not download feed at s3://cataloguedev/gtfs/tampere-20170418T145943-02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.
14:59:45.400 [Thread-11] WARN  c.c.d.manager.models.FeedVersion - No GTFS feed exists for version: tampere-20170418T145943+02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.zip
Building network
14:59:45.443 [Thread-12] INFO  c.c.d.e.j.ProcessGtfsSnapshotMerge - Cleared old data
14:59:45.444 [Thread-12] INFO  com.conveyal.gtfs.GTFSCache - Attempting to download cached GTFS MapDB.
14:59:45.478 [Thread-12] WARN  com.conveyal.gtfs.GTFSCache - DB file for key gtfs/tampere-20170418T145943-02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167 does not exist on S3.
14:59:45.478 [Thread-12] INFO  com.conveyal.gtfs.GTFSCache - Loading feed from local cache directory...
14:59:45.478 [Thread-12] INFO  com.conveyal.gtfs.GTFSCache - Feed not found locally, downloading from S3.
14:59:45.506 [Thread-12] ERROR com.conveyal.gtfs.GTFSCache - Could not download feed at s3://cataloguedev/gtfs/tampere-20170418T145943-02-10e9ec1c-a6c7-418e-95f9-9eb4d911f167.
java.lang.NullPointerException
	at com.conveyal.datatools.manager.models.FeedVersion.getGtfsFeed(FeedVersion.java:181)
	at com.conveyal.datatools.editor.jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:120)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-12" spark.HaltException
	at spark.Service.halt(Service.java:437)
	at spark.Spark.halt(Spark.java:854)
	at com.conveyal.datatools.editor.jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:459)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by landonreed** [comment]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zbouziane](https://github.com/zbouziane)**
_Wednesday Apr 19, 2017 at 13:58 GMT_

----

Config server.yml
------------------
```
application:
  assets_bucket: cataloguedev
  public_url: http://localhost:9000
  port: 4000
  data:
    mapdb: /Users/zbouziane/Data/cataloguedev/mapdb
    gtfs: /Users/zbouziane/Data/cataloguedev/gtfs
    editor_mapdb: /Users/zbouziane/Data/cataloguedev/editor
    regions: /Users/zbouziane/Data/cataloguedev/geojson
    gtfs_s3_bucket: cataloguedev
    s3_credentials_file: /Users/zbouziane/.aws/credentials
    use_s3_storage: true
modules:
  enterprise:
    enabled: false
  editor:
    enabled: true
  alerts:
    enabled: false
    use_extension: xyz
  sign_config:
    enabled: false
  user_admin:
    enabled: true
  validator:
    enabled: true
  deployment:
    enabled: false
  gtfsapi:
    enabled: true
    load_on_fetch: false
    load_on_startup: false
    use_extension: xyz
    update_frequency: 3600 # in seconds
extensions:
  transitland:
    enabled: true
    api: https://transit.land/api/v1/feeds
  transitfeeds:
    enabled: true
    api: http://api.transitfeeds.com/v1/getFeeds
    key: your-api-key
```

**Comment by landonreed** [comment]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zbouziane](https://github.com/zbouziane)**
_Thursday Apr 20, 2017 at 10:31 GMT_

----

It seems GTFSCache doesn't copy files from local system to AWS bucket!
