### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#26]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zbouziane](https://github.com/zbouziane)**
_Wednesday Apr 19, 2017 at 14:10 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/9_

----

```
$ mvn test
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.conveyal.datatools.editor.ProcessGtfsSnapshotMergeTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/zbouziane/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/zbouziane/.m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16:03:53,041 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:03:53,041 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:03:53,042 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/zbouziane/tmp/tmp/datatools-server/target/classes/logback.xml]
16:03:53,044 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:03:53,044 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/zbouziane/.m2/repository/com/conveyal/osm-lib/1.1.0-SNAPSHOT/osm-lib-1.1.0-SNAPSHOT.jar!/logback.xml]
16:03:53,044 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/zbouziane/tmp/tmp/datatools-server/target/classes/logback.xml]
16:03:53,158 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:03:58,171 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:03:58,178 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:03:58,203 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:03:58,254 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
16:03:58,254 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:03:58,254 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:03:58,255 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@22eeefeb - Registering current configuration as safe fallback point

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
17/04/19 16:03:58.263 [main] INFO  com.conveyal.datatools.DatatoolsTest - DatatoolsTest setup
17/04/19 16:03:58.461 [main] INFO  c.c.datatools.manager.DataManager - Loading env.yml: ../configurations/gtfs.works/dev/settings.yml
17/04/19 16:03:58.462 [main] INFO  c.c.datatools.manager.DataManager - Loading server.yml: ../configurations/gtfs.works/dev/server.yml
java.io.FileNotFoundException: ../configurations/gtfs.works/dev/settings.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.conveyal.datatools.manager.DataManager.loadConfig(DataManager.java:307)
	at com.conveyal.datatools.manager.DataManager.main(DataManager.java:78)
	at com.conveyal.datatools.DatatoolsTest.setUp(DatatoolsTest.java:25)
	at com.conveyal.datatools.LoadFeedTest.setUp(LoadFeedTest.java:28)
	at com.conveyal.datatools.editor.ProcessGtfsSnapshotMergeTest.setUp(ProcessGtfsSnapshotMergeTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
17/04/19 16:03:58.466 [main] INFO  com.conveyal.datatools.LoadFeedTest - ProcessGtfsSnapshotMergeTest setup
17/04/19 16:03:58.479 [main] WARN  c.c.datatools.manager.DataManager - Config property application.data.mapdb not found
...
```

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Wednesday Apr 19, 2017 at 14:48 GMT_

----

05884e40f2d01dcd63286c78f6deca87ff621097 (or latest dev) fixes this.
