### ISSUE TITLE
Fail of Uploading In Local Storage Mode 

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#28]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zbouziane](https://github.com/zbouziane)**
_Thursday Apr 20, 2017 at 10:37 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/11_

----

With use_s3_storage set to false:
```
17/04/20 12:14:10.621 [Thread-14] WARN  com.conveyal.gtfs.BaseGTFSCache - Feed tampere-20170420T121408+02-f6a79e00-b150-4725-b385-712826a46351 not found locally
java.lang.NullPointerException
	at com.conveyal.datatools.manager.models.FeedVersion.getGtfsFeed(FeedVersion.java:182)
	at com.conveyal.datatools.editor.jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:130)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Nov 13, 2018 at 17:43 GMT_

----

This code path has been significantly altered and no longer produces this NPE.
