### ISSUE TITLE
Reversed Trip Validation raises a NullPointerException

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#32]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zbouziane](https://github.com/zbouziane)**
_Friday Apr 28, 2017 at 13:25 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/15_

----

```
...
13:21:29.491 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - DuplicateStopsValidator finished in 2092 milliseconds.
13:21:29.492 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - HopSpeedsReasonableValidator finished in 0 milliseconds.
13:21:29.630 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - MisplacedStopValidator finished in 137 milliseconds.
13:21:29.632 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - NamesValidator finished in 1 milliseconds.
13:21:32.257 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - OverlappingTripsValidator finished in 2625 milliseconds.
13:21:33.109 [Thread-11] ERROR com.conveyal.gtfs.GTFSFeed - Could not run ReversedTripsValidator validator.
java.lang.NullPointerException
	at com.conveyal.gtfs.validator.ReversedTripsValidator.validate(ReversedTripsValidator.java:68)
	at com.conveyal.gtfs.GTFSFeed.validate(GTFSFeed.java:284)
	at com.conveyal.gtfs.GTFSFeed.validate(GTFSFeed.java:301)
	at com.conveyal.datatools.manager.models.FeedVersion.validate(FeedVersion.java:282)
	at com.conveyal.datatools.manager.jobs.ValidateFeedJob.run(ValidateFeedJob.java:45)
	at java.lang.Thread.run(Thread.java:745)
13:21:35.756 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - TripTimesValidator finished in 2643 milliseconds.
13:21:35.761 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - UnusedStopValidator finished in 4 milliseconds.
13:21:35.761 [Thread-11] INFO  com.conveyal.gtfs.GTFSFeed - 8 validators completed in 8362 milliseconds.
13:21:35.761 [Thread-11] INFO  c.c.d.manager.models.FeedVersion - Calculating stats...
13:21:37.948 [Thread-11] INFO  c.c.d.manager.models.FeedVersion - Calculating # of trips per date of service
13:21:51.062 [Thread-11] INFO  c.c.d.manager.models.FeedVersion - Total errors after validation: 9
13:21:51.063 [Thread-11] INFO  c.c.d.manager.models.FeedVersion - Uploading validation json to S3
...
```

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Friday Apr 28, 2017 at 14:34 GMT_

----

@zbouziane could you send me the feed that's causing the NPE?

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Nov 13, 2018 at 17:20 GMT_

----

This code path is no longer in use (GTFSFeed was replaced with GTFS). Closing.
