### ISSUE TITLE
Fix deployment documentation

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#40]
<a href="https://github.com/l-vincent-l"><img src="https://avatars0.githubusercontent.com/u/2757318?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [l-vincent-l](https://github.com/l-vincent-l)**
_Tuesday Jul 11, 2017 at 13:34 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/23_

----

At the page : 
http://conveyal-data-tools.readthedocs.io/en/dev/dev/deployment/

It is said you have to run : 
`$ java -jar target/dt-v1.0.0.jar /path/to/env.yml /path/to/server.yml`
to build the java package, I think you have to run : 
`$ mvn package -DskipTests`

**Comment by landonreed** [comment]
<a href="https://github.com/xaverio"><img src="https://avatars3.githubusercontent.com/u/10834471?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xaverio](https://github.com/xaverio)**
_Friday Aug 04, 2017 at 08:10 GMT_

----

@l-vincent-l i think the same. At the moment also without -DskipTests build  process ends successfully with some warning.
especially this:
```
[WARNING] Map in class org.apache.maven.plugins.shade.resource.ManifestResourceTransformer declares value type as: class java.util.jar.Attributes but saw: class java.lang.String at runtime"
"[WARNING] Some problems were encountered while building the effective model for com.conveyal:datatools-server:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 68, column
```

So when try to run :
```
$ java -jar target/datatools-server-1.0.0.jar 
no main manifest attribute, in target/datatools-server-1.0.0.jar
```

i tried to pass the main class (as stated in pom.xml)
```
$ java -cp target/datatools-server-1.0.0.jar com.conveyal.datatools.manager.DataManager
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```
Any suggestions?

my env:
Apache Maven 3.5.0 
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_131/jre
Default locale: en_US, platform encoding: UTF-8
Centos 6.9 name: "linux", version: "2.6.32-696.6.3.el6.x86_64", arch: "amd64", family: "unix"

**Comment by landonreed** [comment]
<a href="https://github.com/WaliedA"><img src="https://avatars1.githubusercontent.com/u/29200703?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WaliedA](https://github.com/WaliedA)**
_Tuesday Aug 15, 2017 at 14:50 GMT_

----

l-vincent-l  did you managed to get this runing

**Comment by landonreed** [comment]
<a href="https://github.com/l-vincent-l"><img src="https://avatars0.githubusercontent.com/u/2757318?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [l-vincent-l](https://github.com/l-vincent-l)**
_Wednesday Aug 16, 2017 at 08:15 GMT_

----

Yes, I'm closing the issue, you just have to run : `mvn package` the tests are run in this command.
