### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown during a GTFS file upload

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#53]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zbouziane](https://github.com/zbouziane)**
_Tuesday Sep 19, 2017 at 08:08 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/36_

----

On `mongo-pojo` branch at commit number `2b91f71e98384f51e0d57d973a00e7c5731ab40a`:

```
sept. 19 09:56:55.178 [pool-2-thread-1] INFO  com.conveyal.osmlib.PBFInput - Done parsing PBF.
sept. 19 09:56:55.179 [pool-2-thread-1] INFO  com.conveyal.osmlib.PBFInput - Read 0 nodes, 0 ways, 0 relations.
sept. 19 09:56:55.282 [pool-2-thread-1] INFO  com.conveyal.r5.streets.StreetLayer - Making street edges from OSM ways...
sept. 19 09:56:55.293 [pool-2-thread-1] WARN  c.c.d.manager.models.FeedVersion - Unknown error encountered while building network for TISSEO2-20170919T095640-02-2341da9d-c09c-48fc-8dbd-7e94c7683f0f.zip.
java.lang.ArrayIndexOutOfBoundsException: Attempt to seek beyond end of edge store
	at com.conveyal.r5.streets.EdgeStore$Edge.seek(EdgeStore.java:348)
	at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:273)
	at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:170)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:166)
	at com.conveyal.r5.transit.TransportNetwork.fromFeeds(TransportNetwork.java:133)
	at com.conveyal.datatools.manager.models.FeedVersion.buildTransportNetwork(FeedVersion.java:522)
	at com.conveyal.datatools.manager.jobs.BuildTransportNetworkJob.run(BuildTransportNetworkJob.java:31)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.conveyal.datatools.common.status.MonitorableJob.jobFinished(MonitorableJob.java:83)
	at com.conveyal.datatools.manager.jobs.ValidateFeedJob.run(ValidateFeedJob.java:50)
	at com.conveyal.datatools.manager.jobs.ProcessSingleFeedJob.run(ProcessSingleFeedJob.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
``

**Comment by landonreed** [comment]
<a href="https://github.com/abyrd"><img src="https://avatars0.githubusercontent.com/u/112871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abyrd](https://github.com/abyrd)**
_Tuesday Sep 19, 2017 at 08:15 GMT_

----

Bonjour, the PBF file pulled in is empty ("Read 0 nodes, 0 ways, 0 relations.") We should handle this situation better, but there is something wrong with the input data. Is this being pulled from Conveyal's OSM server? If so this is the problem - that server is only loaded with North American data at the moment. I am migrating it to the version that uses RDBMS instead of MapDB.

**Comment by landonreed** [comment]
<a href="https://github.com/zbouziane"><img src="https://avatars0.githubusercontent.com/u/715301?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zbouziane](https://github.com/zbouziane)**
_Tuesday Sep 19, 2017 at 08:39 GMT_

----

Thanks @abyrd, The PBF is effectively empty. It was pulled from Conveyal's OSM server. Do you think we should deploy our own OSM server? which branch and commit you advise us?

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Wednesday Sep 20, 2017 at 12:31 GMT_

----

@zbouziane, because r5 (the package that handles creating the transport network in datatools-server) is still using the previous version of gtfs-lib, I would suggest setting `modules.validator.enabled` to `false` for the time being.  Unless there is an immediate need to utilize this feature, I think we should leave it disabled for the time being (until we can upgrade r5 to use the same `sql-loader` branch of gtfs-lib).

Another reason we may want to disable this for now is that this is a feature that @abyrd has helped identify as more or less unstable because we typically run r5 on separate servers for individual networks, rather than as an internal library with potentially multiple networks.  Because of this fact,  multiple transportNetworks have the potential to be large memory leaks and are not currently cached in datatools-server.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Monday Nov 12, 2018 at 18:27 GMT_

----

`BuildTransportNetworkJob` is no longer a job run on uploaded feeds because R5 has been removed from the application. Closing this issue.
