### ISSUE TITLE
r5 NPE raised with the attached GTFS

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-server#75]
<a href="https://github.com/cgalant"><img src="https://avatars1.githubusercontent.com/u/1777403?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cgalant](https://github.com/cgalant)**
_Tuesday Oct 31, 2017 at 09:52 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/56_

----

on mongo-pojo branch, when I upload the attached GTFS file, a NPE is raised from r5 lib.
I am pretty sure it wasn't in previous version.

Anyway, whether or not some data are missing in the file , NPE should not occur.

`11:02:56.935 [pool-2-thread-1] WARN  c.c.d.manager.models.FeedVersion - Unknown error encountered while building network for RATP_GTFS_BUS_20-20171031T110251-01-81893661-6226-4a5d-b12b-17b2c22ca0af.zip.
11:02:56.940 [pool-2-thread-1] WARN  c.c.d.m.jobs.ProcessSingleFeedJob - Not storing version RATP_GTFS_BUS_20-20171031T110251-01-81893661-6226-4a5d-b12b-17b2c22ca0af.zip because error occurred during processing.
java.lang.NullPointerException
	at com.conveyal.r5.streets.StreetLayer.getVertexIndexForOsmNode(StreetLayer.java:883)
	at com.conveyal.r5.streets.StreetLayer.makeEdge(StreetLayer.java:927)
	at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:264)
	at com.conveyal.r5.streets.StreetLayer.loadFromOsm(StreetLayer.java:170)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:166)
	at com.conveyal.r5.transit.TransportNetwork.fromFeeds(TransportNetwork.java:133)
	at com.conveyal.datatools.manager.models.FeedVersion.buildTransportNetwork(FeedVersion.java:365)
	at com.conveyal.datatools.manager.jobs.BuildTransportNetworkJob.jobLogic(BuildTransportNetworkJob.java:33)
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:108)
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

[RATP_GTFS_BUS_20.zip](https://github.com/catalogueglobal/datatools-server/files/1430226/RATP_GTFS_BUS_20.zip)

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Oct 31, 2017 at 16:46 GMT_

----

@cgalant, so I can raise this issue in the r5 library, but the exception should be caught during the `BuildTransportNetwork` job.  I think we're handling it as best we can within datatools-server at the moment.  Also, contrary to the log statement, the feed version **is** being stored properly.  The only effect of the NPE is to fail the `BuildTransportNetwork` job.  The `status` for the job will have `error` set to `true` and the client will get a notification about why this job failed.

The underlying cause here is that the osm extractor is currently not running for areas outside of North America.  As I mentioned on the phone, this is actually only an issue when the `validator` module is enabled (validator being an incorrect name for r5 transport network builder).

@abyrd do you have any thoughts here?

**Comment by landonreed** [comment]
<a href="https://github.com/abyrd"><img src="https://avatars0.githubusercontent.com/u/112871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abyrd](https://github.com/abyrd)**
_Wednesday Nov 08, 2017 at 12:48 GMT_

----

Since we have recommended that the R5 network building module be disabled for deployments of the upcoming release, this recommendation is included in the documentation, and we've renamed the module to make it clear that it's not enabling/disabling _all_ validation, we can resolve this in a future release. This module is just a starting point for advanced validation techniques, and we will want to expand and refine the basic RDBMS based validation before we move on to that.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Nov 13, 2018 at 17:14 GMT_

----

R5 has been removed from the application, so we can close this.
